# Generated by Django 3.0.3 on 2020-03-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='price',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
